(function() {var implementors = {};
implementors["amfi"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"struct\" href=\"amfi/struct.NavRecord.html\" title=\"struct amfi::NavRecord\">NavRecord</a>",synthetic:true,types:["amfi::NavRecord"]},{text:"impl&lt;T&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"struct\" href=\"amfi/struct.NavRecordIterator.html\" title=\"struct amfi::NavRecordIterator\">NavRecordIterator</a>&lt;T&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;T: <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a>,&nbsp;</span>",synthetic:true,types:["amfi::NavRecordIterator"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"enum\" href=\"amfi/enum.Error.html\" title=\"enum amfi::Error\">Error</a>",synthetic:true,types:["amfi::Error"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"enum\" href=\"amfi/enum.FundMaturity.html\" title=\"enum amfi::FundMaturity\">FundMaturity</a>",synthetic:true,types:["amfi::FundMaturity"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"enum\" href=\"amfi/enum.FundPlan.html\" title=\"enum amfi::FundPlan\">FundPlan</a>",synthetic:true,types:["amfi::FundPlan"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
